spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_prod
    username: root
    password: SanSak@123
    driver-class-name: com.mysql.cj.jdbc.Driver
build:
  version: "1.2"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John TEST - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
