spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
build:
  version: "1.2"

accounts:
  message: "Welcome to EazyBank accounts related webhook1 APIs "
  contactDetails:
    name: "John test - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345



