spring:
  config:
    activate:
      on-profile: "qa"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_qa
    username: root
    password: SanSak@123
    driver-class-name: com.mysql.cj.jdbc.Driver
build:
  version: "1.1"

loans:
  message: "Welcome to EazyBank loans related webhook APIs "
  contactDetails:
    name: "John test - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
